# Generated by Django 3.1.2 on 2020-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('complaint', models.CharField(max_length=1000, null=True)),
                ('contact', models.IntegerField()),
                ('booking_code', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
