# Generated by Django 3.1.2 on 2020-11-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Resolved', 'Resolved'), ('In Process', 'In Process')], default='New', max_length=120),
        ),
    ]
