# Generated by Django 3.1.2 on 2020-11-26 16:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Bhutan', 'Bhutan'), ('Nepal', 'Nepal')], max_length=120)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hotel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(choices=[('Paro', 'Paro'), ('Thimpu', 'Thimpu'), ('Punakha', 'Punakha'), ('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Lumbini', 'Lumbini')], max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.URLField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('rooms', models.IntegerField()),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.category')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='')),
                ('image_Description', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
