# Generated by Django 3.1.2 on 2020-11-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='locations',
            new_name='location',
        ),
    ]
