# Generated by Django 3.1.2 on 2020-11-28 11:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201126_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='hkajsdfh'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='location_overview',
            field=models.CharField(default='Set against the Himalayas, this polished, palatial hotel built to resemble a 17th-century fortress overlooks the Paro River and is 4 km from the airport, and 7 km from Rinpung Dzong, a famed Buddhist monastery/fortress.', max_length=250),
        ),
    ]
