# Generated by Django 3.1.2 on 2020-11-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250, null=True)),
                ('guest', models.IntegerField()),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(default='India', max_length=50, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('bookingcode', models.CharField(max_length=14)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.FloatField(null=True)),
                ('cname', models.CharField(max_length=50, null=True)),
                ('ccnum', models.CharField(max_length=16, null=True)),
                ('expmonth', models.CharField(max_length=50, null=True)),
                ('expyear', models.CharField(max_length=50, null=True)),
                ('cvv', models.CharField(max_length=3, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
