# Generated by Django 3.1.2 on 2020-11-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_bookinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='country',
        ),
    ]
