# Generated by Django 3.1.2 on 2020-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_bookinginfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
