# Generated by Django 3.1.2 on 2020-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_bookinginfo_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='check_in',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='check_out',
            field=models.CharField(max_length=50),
        ),
    ]
