# Generated by Django 3.1.2 on 2020-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='location',
            field=models.CharField(choices=[('Paro', 'Paro'), ('Thimpu', 'Thimpu'), ('Punakha', 'Punakha'), ('Kathmandu', 'Kathmandu'), ('Pokhara', 'Pokhara'), ('Lumbini', 'Lumbini')], max_length=20, null=True),
        ),
    ]
